# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Checks-out the community flutter action
      - uses: subosito/flutter-action@v2

      # Basic flutter commands
      - name: Check Flutter version
        run: flutter --version
        
      - name: Get project packages
        run: flutter pub get
        
      - name: Do Flutter tests
        run: flutter test
        
      - name: Run repo lint check
        uses: kitek/dartanalyzer-annotations-action@v1  
        env:
          GITHUB_TOKEN: ${{ secrets.GITSEARCH_ACTION_TOKEN }}
        with:
          check_name: 'Check code style'
          commit_sha: ${{ github.event.pull_request.head.sha }}
      
      #Android build
      - name: Flutter build apk test
        run: flutter build apk
      - name: Flutter build appbundle
        run: flutter build appbundle      
         
  buildIOS:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Checks-out the community flutter action
      - uses: subosito/flutter-action@v2
      
      # Basic flutter commands
      - name: Check Flutter version
        run: flutter --version
        
      - name: Get project packages
        run: flutter pub get
        
      - name: Do Flutter tests
        run: flutter test
        
      - name: Run repo lint check
        uses: kitek/dartanalyzer-annotations-action@v1  
        env:
          GITHUB_TOKEN: ${{ secrets.GITSEARCH_ACTION_TOKEN }}
        with:
          check_name: 'Check code style'
          commit_sha: ${{ github.event.pull_request.head.sha }}

      #IOS build
      - name: Flutter build IOS unsigned ipa
        run: flutter build ios --release --no-codesign
